// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/widgets": {
    params: {};
  };
  "/counter": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/widgets" | "/counter";
  };
  "./routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/widgets" | "/counter";
  };
  "./routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "./routes/widgets.tsx": {
    id: "routes/widgets";
    page: "/widgets";
  };
  "./routes/counter.tsx": {
    id: "routes/counter";
    page: "/counter";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/layout": typeof import("./src/./routes/layout.tsx");
  "routes/index": typeof import("./src/./routes/index.tsx");
  "routes/widgets": typeof import("./src/./routes/widgets.tsx");
  "routes/counter": typeof import("./src/./routes/counter.tsx");
};