// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemixAspireStarter.Data;

#nullable disable

namespace remix_aspire_starter.Data.Migrations
{
  [DbContext(typeof(ApplicationDbContext))]
  [Migration("20251029001307_InitialCreate")]
  partial class InitialCreate
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "9.0.10")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("RemixAspireStarter.Models.Widget", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("Name")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<int>("Quantity")
                      .HasColumnType("integer");

            b.HasKey("Id");

            b.ToTable("Widgets");
          });
#pragma warning restore 612, 618
    }
  }
}
